<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/master.Master" AutoEventWireup="true" CodeBehind="CommitteeMangement.aspx.cs" Inherits="Committee.Views.Forms.CommitteeMangement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form role="form" class="form-horizontal form-groups-bordered" runat="server" id="f1">
    <div class="form-group">
								<%--<label for="field-1" class="col-sm-3 control-label">حفظ :</label>--%>
        <div class="col-sm-3">
							 <asp:TextBox ID="txtCommitteeName" runat="server" CssClass="form-control"></asp:TextBox>
            </div>
								<div class="col-sm-3">
                                    <asp:Button ID="btnSearch" Font-Size="Medium" runat="server" Text="بحث"  CssClass="btn btn-success" OnClick="btnSearch_Click" />

								</div>
         <div class="col-sm-4">
            </div>
          <div class="col-sm-1">
          <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-white" PostBackUrl="~/Views/Forms/Dashboard.aspx" > الغاء</asp:LinkButton>

            </div>
								<div class="col-sm-1">
                                   <asp:LinkButton ID="btnaddNewCommittee" runat="server" CssClass="btn btn-blue" OnClick="btnaddNewCommittee_Click" >اضافة لجنة جديدة</asp:LinkButton>

								</div>

							</div>
    <div class="form-group">
                        <div class="col-sm-5">
                            <asp:GridView ID="gvCommittee" runat="server" CssClass="table table-middle nowrap demo-dynamic-tables-1" Font-Size="Medium" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ForeColor="Black" GridLines="Vertical" OnDataBound="gvCommittee_DataBound" OnPageIndexChanged="gvCommittee_PageIndexChanged" OnPageIndexChanging="gvCommittee_PageIndexChanging" OnRowCancelingEdit="gvCommittee_RowCancelingEdit" OnRowDataBound="gvCommittee_RowDataBound" OnRowDeleting="gvCommittee_RowDeleting" OnRowEditing="gvCommittee_RowEditing" OnRowUpdating="gvCommittee_RowUpdating" OnSelectedIndexChanged="gvCommittee_SelectedIndexChanged" OnSelectedIndexChanging="gvCommittee_SelectedIndexChanging" OnSorting="gvCommittee_Sorting" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px">
                                <AlternatingRowStyle BackColor="#CCCCCC" />
                                <EditRowStyle ForeColor="Blue" />
                                <FooterStyle BackColor="#CCCCCC" />
                                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#808080" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#383838" />
                            </asp:GridView>
                        </div>

                    </div>
        </form>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
