<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/master.Master" AutoEventWireup="true" CodeBehind="CommitteeMangement.aspx.cs" Inherits="Committee.Views.Forms.CommitteeMangement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   
    			  <asp:ScriptManager ID="ScriptManager1" EnableCdn="False" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePaneltypeOfservice" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
    <div class="form-group">
								<%--<label for="field-1" class="col-sm-3 control-label">حفظ :</label>--%>
        <div class="col-sm-3">
							 <asp:TextBox ID="txtCommitteeName" runat="server" placeholder="ابحث بإسم اللجنة أو التاريخ"  CssClass="form-control"></asp:TextBox>
            </div>
								<div class="col-sm-3">
                                    <asp:Button ID="btnSearch" Font-Size="Medium" runat="server" Text="بحث"  CssClass="btn btn-success" OnClick="btnSearch_Click" />

								</div>
         <div class="col-sm-3">
            </div>
          <div class="col-sm-1">
          <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-white" PostBackUrl="~/Views/Forms/Dashboard.aspx" > الغاء</asp:LinkButton>

            </div>
								<div class="col-sm-2">
                                   <asp:LinkButton ID="btnaddNewCommittee" runat="server" CssClass="btn btn-blue" OnClick="btnaddNewCommittee_Click" >اضافة لجنة جديدة</asp:LinkButton>

								</div>

							</div>
    <div class="form-group">
                        <div class="col-sm-12">
                            <asp:GridView ID="gvCommittee" runat="server" CssClass="table table-middle nowrap demo-dynamic-tables-1" Font-Size="Small" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ForeColor="Black" GridLines="Horizontal"  OnPageIndexChanging="gvCommittee_PageIndexChanging" OnRowDataBound="gvCommittee_RowDataBound" OnRowDeleting="gvCommittee_RowDeleting" OnRowEditing="gvCommittee_RowEditing" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" AutoGenerateSelectButton="True" OnSelectedIndexChanged="gvCommittee_SelectedIndexChanged" OnSelectedIndexChanging="gvCommittee_SelectedIndexChanging" OnSorting="gvCommittee_Sorting1">
                                <AlternatingRowStyle BackColor="#CCCCCC" />
                                <EditRowStyle ForeColor="Blue" />
                                <FooterStyle BackColor="#CCCCCC" />
                                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#808080" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#383838" />
                            </asp:GridView>
                        </div>

                    </div>
     </ContentTemplate>
            </asp:UpdatePanel>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
