<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/master.Master" AutoEventWireup="true" CodeBehind="DepartmentMangement.aspx.cs" Inherits="Committee.Views.Forms.DepartmentMangement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      <asp:ScriptManager ID="ScriptManager1" EnableCdn="False" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePaneltypeOfservice" runat="server" UpdateMode="Conditional">
            <ContentTemplate>  
    <div class="form-group">
								<%--<label for="field-1" class="col-sm-3 control-label">حفظ :</label>--%>
        <div class="col-sm-3">
							 <asp:TextBox ID="txtSearch" runat="server" placeholder="ابحث بإسم الادارة" CssClass="form-control"></asp:TextBox>
            </div>
								<div class="col-sm-3">
                                    <asp:Button ID="btnSearch" Font-Size="Medium" runat="server" Text="بحث"  CssClass="btn btn-success" OnClick="btnSearch_Click"/>

								</div>
         <div class="col-sm-3">
            </div>
          <div class="col-sm-1">
          <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-white" PostBackUrl="~/Views/Forms/Dashboard.aspx" > الغاء</asp:LinkButton>

            </div>
								<div class="col-sm-2">
                                   <asp:LinkButton ID="btnaddMember" runat="server" CssClass="btn btn-blue" OnClick="btnaddDept_Click" >اضافة ادارة جديدة</asp:LinkButton>

								</div>

							</div>
    <div class="form-group">
                        <div class="col-sm-12">
                              <asp:GridView ID="gvDepts" runat="server" Font-Size="Small" CssClass="table-striped table" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="Black" OnDataBound="gvDepts_DataBound" OnPageIndexChanged="gvDepts_PageIndexChanged" OnPageIndexChanging="gvDepts_PageIndexChanging" OnRowCancelingEdit="gvDepts_RowCancelingEdit" OnRowDataBound="gvDepts_RowDataBound" OnRowDeleting="gvDepts_RowDeleting" OnRowEditing="gvDepts_RowEditing" OnRowUpdating="gvDepts_RowUpdating" OnSelectedIndexChanged="gvDepts_SelectedIndexChanged" OnSelectedIndexChanging="gvDepts_SelectedIndexChanging" OnSorting="gvDepts_Sorting" PageSize="5" >
                                        <FooterStyle BackColor="#CCCCCC" />
                                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Center" />
                                        <RowStyle BackColor="White" />
                                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                        <SortedAscendingHeaderStyle BackColor="#808080" />
                                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                        <SortedDescendingHeaderStyle BackColor="#383838" /> 
                   </asp:GridView>
                        </div>

                    </div>
      
</ContentTemplate>
            </asp:UpdatePanel>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
