<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/master.Master" AutoEventWireup="true" CodeBehind="Department.aspx.cs" Inherits="Committee.Views.Forms.Department" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      
  
           <div class="main-content col-md-12">
	
		
		<hr />
		
					<ol class="breadcrumb bc-3" >
								<li>
						<a href="Dashboard.aspx"><i class="fa-home"></i>الشاشات</a>
					</li>
							<li>
		
									<a href="Committe.aspx">الإدارات</a>
							</li>
						<li class="active">
		
									<strong>
               <asp:Label ID="lblDeptNew" runat="server" Text="Label"></asp:Label></strong>
							</li>
							</ol>
					
		<h2>
                   <asp:Label ID="lblDeptH1" runat="server" Text="Label"></asp:Label></h2>
		<br />
		
		
		<div class="row col-md-12">
			<div class="col-md-12">
				
				<div class="panel panel-primary" data-collapsed="0">
				
					<div class="panel-heading">
						<div class="panel-title">
						إدارة
						</div>
						
						<div class="panel-options">
							<a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a>
							<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
							<a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a>
							<a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
						</div>
					</div>
					
					<div class="panel-body">
							
					<div class="form-group">
								<%--<label for="field-1" class="col-sm-3 control-label">حفظ :</label>--%>
      <div class="col-sm-4">

      </div>
         <div class="col-sm-4">
            </div>

          <div class="col-sm-1">
          <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-white" PostBackUrl="~/Views/Forms/DepartmentMangement.aspx" Text="الغاء" > </asp:LinkButton>

            </div>
								<div class="col-sm-1">
<%--                                    <asp:Button ID="btnAdd1" runat="server"  Text="حفظ" OnClick="btnAdd1_Click" ValidationGroup="a" CssClass="btn btn-success" />--%>
                                   <asp:LinkButton ID="btnSave" Font-Size="Medium" runat="server" Text="حفظ" OnClick="btnSave_Click" ValidationGroup="a" CssClass="btn btn-success">حفظ</asp:LinkButton>

								</div>
                       
							</div>

					

							<div class="form-group">
								<label for="field-1" class="col-sm-3 control-label">اسم الإدارة :</label>
							 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="هذا الحقل مطلوب" Font-Size="Large" ValidationGroup="a" ForeColor="Red" ControlToValidate="txtDeptName"></asp:RequiredFieldValidator>

								<div class="col-sm-5">
                        <asp:TextBox ID="txtDeptName"  runat="server" CssClass="form-control" ValidationGroup="a"></asp:TextBox>
								</div>
							</div>
							
							<div class="form-group">
								<label for="field-2" class="col-sm-3 control-label">عنوان الإدارة :</label>
									  <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="هذا الحقل مطلوب" Font-Size="Large" ValidationGroup="a" ForeColor="Red" ControlToValidate="txtDeptAddress"></asp:RequiredFieldValidator>
								
								<div class="col-sm-5">

                        <asp:TextBox ID="txtDeptAddress" runat="server"  CssClass="form-control" ValidationGroup="a"></asp:TextBox>
								</div>
							</div>
                        <div class="form-group">
                        <div class="col-sm-12">
                              <asp:GridView ID="gvCommittee" Visible="false" runat="server" CssClass="table-striped table" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="Black" OnDataBound="gvCommittee_DataBound" OnPageIndexChanged="gvCommittee_PageIndexChanged" OnPageIndexChanging="gvCommittee_PageIndexChanging" OnRowCancelingEdit="gvCommittee_RowCancelingEdit" OnRowDataBound="gvCommittee_RowDataBound" OnRowDeleting="gvCommittee_RowDeleting" OnRowEditing="gvCommittee_RowEditing" OnRowUpdating="gvCommittee_RowUpdating" OnSelectedIndexChanged="gvCommittee_SelectedIndexChanged" OnSelectedIndexChanging="gvCommittee_SelectedIndexChanging" OnSorting="gvCommittee_Sorting" PageSize="5" >
                                        <FooterStyle BackColor="#CCCCCC" />
                                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Center" />
                                        <RowStyle BackColor="White" />
                                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                        <SortedAscendingHeaderStyle BackColor="#808080" />
                                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                        <SortedDescendingHeaderStyle BackColor="#383838" /> 
                   </asp:GridView>
                        </div>

                    </div>
                        </div>
                    </div>
                </div>
            </div>
               </div>
                        
                     
</asp:Content>

