<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/master.Master" AutoEventWireup="true" CodeBehind="MemberMangement.aspx.cs" Inherits="Committee.Views.Forms.MemberMangement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      
    		
    <div class="form-group">
								<%--<label for="field-1" class="col-sm-3 control-label">حفظ :</label>--%>
        <div class="col-sm-3">
							 <asp:TextBox ID="txtSearch" runat="server" placeholder="ابحث بإسم العضو أو رقم التليفون" CssClass="form-control"></asp:TextBox>
            </div>
								<div class="col-sm-3">
                                    <asp:Button ID="btnSearch" Font-Size="Medium" runat="server" Text="بحث"  CssClass="btn btn-success" OnClick="btnSearch_Click"/>

								</div>
         <div class="col-sm-3">
            </div>
          <div class="col-sm-1">
          <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-white" PostBackUrl="~/Views/Forms/Dashboard.aspx" > الغاء</asp:LinkButton>

            </div>
								<div class="col-sm-2">
                                   <asp:LinkButton ID="btnaddMember" runat="server" CssClass="btn btn-blue" OnClick="btnaddMember_Click" >اضافة عضو جديد</asp:LinkButton>

								</div>

							</div>
    <div class="form-group">
                        <div class="col-sm-12">
                              <asp:GridView ID="gvMembers" runat="server" Font-Size="Small" CssClass="table-striped table" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="Black" OnDataBound="gvMembers_DataBound" OnPageIndexChanged="gvMembers_PageIndexChanged" OnPageIndexChanging="gvMembers_PageIndexChanging" OnRowCancelingEdit="gvMembers_RowCancelingEdit" OnRowDataBound="gvMembers_RowDataBound" OnRowDeleting="gvMembers_RowDeleting" OnRowEditing="gvMembers_RowEditing" OnRowUpdating="gvMembers_RowUpdating" OnSelectedIndexChanged="gvMembers_SelectedIndexChanged" OnSelectedIndexChanging="gvMembers_SelectedIndexChanging" OnSorting="gvMembers_Sorting" PageSize="5" >
                                        <FooterStyle BackColor="#CCCCCC" />
                                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Center" />
                                        <RowStyle BackColor="White" />
                                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                        <SortedAscendingHeaderStyle BackColor="#808080" />
                                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                        <SortedDescendingHeaderStyle BackColor="#383838" /> 
                   </asp:GridView>
                        </div>

                    </div>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
